### ISSUE TITLE
Problem loading pods

### ISSUE THREAD

**Issue by santigracia** [saul51292/ProductSwipe#1]
After running pod install can't load all the pods

![image](https://cloud.githubusercontent.com/assets/11093718/8732164/a0663d1c-2bb0-11e5-83f3-1fd77aad7903.png)

Thank you.

**Comment by saul51292** [comment]
Hey,

Thanks for reaching out! 
Another person had a similar problem and reached out on the original reddit thread.

Here’s a link to it. 

https://www.reddit.com/r/swift/comments/34la62/just_made_a_swift_tinder_clone_for_clothing/ https://www.reddit.com/r/swift/comments/34la62/just_made_a_swift_tinder_clone_for_clothing/

Check out the comments for the solution

Email me again if it’s still not working.

Thanks,

-Saul

**Comment by barronlroth** [comment]
Any idea why my pods won't fully install? Using cocoapods 0.39.0.beta.3

<img width="839" alt="screenshot 2015-09-11 16 45 41" src="https://cloud.githubusercontent.com/assets/5567884/9825904/a0eaecb2-58a4-11e5-9d01-a605fa151929.png">

**Comment by saul51292** [comment]
Hey, 
Sorry to hear about that. 

I updated the Podfile so it doesnt use project to install the pods but I can’t test it just yet. 
I did push the updated project, so try pulling and re-running ‘pod install’.

Let me know if it works or if you have any other issues. 

Thanks! 
-Saul
